#!/bin/bash
# Script to complete DDP migration for all tasks
# This script provides instructions and patches for completing the DDP migration

echo "======================================================================"
echo "DDP Migration Guide"
echo "======================================================================"
echo ""
echo "✅ Already completed:"
echo "  1. main_segmentation.py - Migrated to DDP"
echo "  2. tasks/segmentation.py - Added rank/world_size support"
echo "  3. run_segmentation.sh - Using torchrun"
echo "  4. core/ddp_utils.py - Created shared DDP utilities"
echo ""
echo "📋 Remaining tasks to complete manually or via agent mode:"
echo ""
echo "1. Update main_detection.py:"
echo "   - Import: from core.ddp_utils import setup_ddp, cleanup_ddp, create_ddp_dataloaders"
echo "   - Replace DataParallel with DDP"
echo "   - Add rank/world_size handling"
echo ""
echo "2. Update main_classification.py:"
echo "   - Same changes as detection"
echo ""
echo "3. Update tasks/detection.py:"
echo "   - Add rank=0, world_size=1 parameters to run_training_loop()"
echo "   - Wrap prints with 'if rank == 0'"
echo "   - Add sampler.set_epoch() for distributed training"
echo ""
echo "4. Update tasks/classification.py:"
echo "   - Same changes as detection"
echo ""
echo "5. Update run_detection.sh:"
echo "   - Replace 'python' with 'torchrun --standalone --nnodes=1 --nproc_per_node=4'"
echo ""
echo "6. Update run_classification.sh:"
echo "   - Same as detection"
echo ""
echo "7. Increase batch sizes for better GPU utilization:"
echo "   - Segmentation: 16 → 32 (8 per GPU × 4 GPUs)"
echo "   - Detection: 64 → 128 (32 per GPU × 4 GPUs)"
echo "   - Classification: 64 → 128 (32 per GPU × 4 GPUs)"
echo ""
echo "======================================================================"
echo "Key Benefits after DDP migration:"
echo "======================================================================"
echo "  • Balanced GPU memory (each GPU ~10-12GB instead of 22GB on main)"
echo "  • 2-3x larger batch sizes possible"
echo "  • Better training stability"
echo "  • Faster training with improved communication"
echo ""
echo "======================================================================"

