#!/bin/bash
# 可视化工具使用说明

echo "======================================================================"
echo "  模型对比可视化工具 - 使用说明"
echo "======================================================================"
echo ""
echo "📁 目录结构："
echo "   visualization/"
echo "   ├── compare_models.py           # 主程序"
echo "   ├── compare_segmentation.sh     # 分割任务对比"
echo "   ├── compare_classification.sh   # 分类任务对比"
echo "   └── results/                    # 可视化结果输出"
echo ""
echo "======================================================================"
echo "  使用方法"
echo "======================================================================"
echo ""
echo "1️⃣  分割任务对比 (ADE20K):"
echo "   cd /home/user/zhoutianjian/Dino_DAGA"
echo "   source activate dinov3_env"
echo "   ./visualization/compare_segmentation.sh"
echo ""
echo "2️⃣  分类任务对比 (CIFAR-100):"
echo "   cd /home/user/zhoutianjian/Dino_DAGA"
echo "   source activate dinov3_env"
echo "   ./visualization/compare_classification.sh"
echo ""
echo "======================================================================"
echo "  已生成的可视化结果"
echo "======================================================================"
echo ""
echo "📊 分割任务 (ADE20K):"
echo "   - 发现改进样本: 155个"
echo "   - 已可视化: 15个最佳改进"
echo "   - 最大mIoU提升: 21.54%"
echo "   - 输出位置: visualization/results/segmentation_ade20k/segmentation/"
echo ""
echo "📊 分类任务 (CIFAR-100):"
echo "   - 发现改进样本: 37个"
echo "   - 已可视化: 10个最佳改进"
echo "   - 最大置信度提升: 0.543"
echo "   - 输出位置: visualization/results/classification_cifar100/classification/"
echo ""
echo "======================================================================"
echo "  技术细节"
echo "======================================================================"
echo ""
echo "🔧 使用GPU: 3, 4, 5, 6 (DataParallel并行)"
echo "🔧 环境: dinov3_env (使用 source activate 激活)"
echo "🔧 自动检测模型架构: 从checkpoint读取model_name"
echo "🔧 自动处理DataParallel: 去除module.前缀"
echo ""
echo "======================================================================"
echo "  可视化内容"
echo "======================================================================"
echo ""
echo "✨ 分割任务可视化包含:"
echo "   - 原始图像"
echo "   - Ground Truth标注"
echo "   - Baseline预测 (带mIoU)"
echo "   - DAGA预测 (带mIoU)"
echo "   - mIoU提升数值"
echo ""
echo "✨ 分类任务可视化包含:"
echo "   - Baseline预测 (错误)"
echo "   - DAGA预测 (正确)"
echo "   - 置信度对比"
echo "   - 真实标签"
echo ""
echo "======================================================================"

